---
title: "Demographic Analysis"
authors: "Debayan Saha (2019113002), Shaurya Dewan (2019101017), Snehal Kumar (2019101003)"
date: "08/04/2023"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

# Basic Setup
```{r}

rm(list = setdiff(ls(), lsf.str()))
library(readxl)
library(ggplot2)
library(fmsb)
library(vcd)
library(explore)
library(corrplot)
library(dplyr)
library(car)
library(rstatix)
library(ggpubr)
library(ez)
library(car)
library(lme4)

demo_data_file <- "../data/PredictingOutcomes_ParticipantDemographics.xlsx"
excel_sheets(demo_data_file)
pred_data_file <- "../data/PredictingOutcomes_ParticipantPredictions.xlsx"
excel_sheets(pred_data_file)
strat_data_file <- "../data/PredictingOutcomes_QualitativeStrategyRatings.xlsx"
excel_sheets(strat_data_file)

```

# Data Organization
```{r}

read_excel_allsheets <- function(filename, tibble = FALSE) {
    sheets <- excel_sheets(filename)
    x <- lapply(sheets, function(X) read_excel(filename, sheet = X))
    x <- lapply(x, as.data.frame)
    names(x) <- sheets
    x
}

pred_data <- read_excel_allsheets(pred_data_file)
demo_data <- read_excel_allsheets(demo_data_file)

data <- pred_data
for(i in names(pred_data)) {       # for-loop over columns
  if(i == "KEY") {
    next
  }
    
  data[[i]] <- left_join(pred_data[[i]], demo_data[[i]], by = "participant_id") %>% 
    select(-ends_with(".y"), study = study.x, generator = generator.x, rate = rate.x) 
  data[[i]]$score_prob <- data[[i]]$score_prob1 + data[[i]]$score_prob2 + data[[i]]$score_prob3
  data[[i]]$score_fin <- data[[i]]$score_fin1 + data[[i]]$score_fin2
  
}

anova <- function(df, study) {
  df$participant_id <- as.factor(df$participant_id)
  df$generator <- as.factor(df$generator)
  df$terminal_streak_length <- as.factor(df$terminal_streak_length)
  df$gender <- as.factor(df$gender)
  df$stocks <- as.factor(df$stocks)
  df$gambling <- as.factor(df$gambling)

  #outlier detection
  print(df %>%
    group_by(terminal_streak_length, generator, stocks) %>%
    identify_outliers(prediction_recode))

  #Shapiro-Wilk test
  print(df %>%
    group_by(terminal_streak_length, generator, stocks) %>%
    shapiro_test(prediction_recode))
  
  #Q-Q plot
  print(ggqqplot(df, "prediction_recode", ggtheme = theme_bw()) +
    facet_grid(terminal_streak_length ~ generator + stocks))
  
  #Levene test for homogeneity of variances
  print(df %>%
    group_by(terminal_streak_length) %>%
    levene_test(prediction_recode ~ generator * stocks))
  
  #Box-m test for sphericity
  # print(box_m(df[, "prediction_recode", drop = FALSE], df$generator))
    
  # aov_orig <- aov(prediction_recode ~ generator * terminal_streak_length + Error(participant_id / terminal_streak_length), data = df)
  # print(summary(aov_orig))
  
  # aov_orig <- ezANOVA(
  #   data = df,
  #   dv = prediction_recode,
  #   wid = participant_id,
  #   within = (terminal_streak_length),
  #   between = c(generator),
  #   type = 3
  # )
  # print(aov_orig)

  # ancova <- aov(prediction_recode ~ generator * gender * terminal_streak_length + Error(participant_id / terminal_streak_length) + age + highest_degree + gambling + score_fin, data = df)
  # print(summary(ancova))

  anova <- ezANOVA(
    data = df,
    dv = prediction_recode,
    wid = participant_id,
    within = (terminal_streak_length),
    between = c(generator, stocks),
    type = 2
  )
  print(anova)

  print("Games-Howell Test")  
  print(games_howell_test(df, prediction_recode ~ generator, conf.level = 0.95, detailed = T))
  print(games_howell_test(df, prediction_recode ~ terminal_streak_length, conf.level = 0.95, detailed = T))
  print(games_howell_test(df, prediction_recode ~ stocks, conf.level = 0.95, detailed = T))

  if (grepl("A", study)) {
    df$prediction_recode <- round(df$prediction_recode / 100)
  }
  
  print("Regression")
  res = glmer(prediction_recode ~ generator + stocks + terminal_streak_length + (1 | participant_id), data = df, family = binomial)
  X = model.matrix(res) # The X matrix!
  sum = summary(res)
  print(sum)
  
  betahat = cbind(sum$coef[,1]) # Estimated fixed effects as a column vector.
  estlogodds = X %*% betahat # Estimated pop mean log odds for each observation.
  # Display estimated pop mean log odds by Hand and Spot
  aggmeans = aggregate(estlogodds, by = list(df$generator, df$stocks, df$terminal_streak_length), FUN = mean)
  print(aggmeans)
}

for(i in names(pred_data)) {       # for-loop over columns
  if(i == "KEY") {
    next
  }
  
  print(i)
  anova(data[[i]], i)
}

```
