---
title: "Demographic Analysis"
authors: "Debayan Saha (2019113002), Shaurya Dewan (2019101017), Snehal Kumar (2019101003)"
date: "08/04/2023"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

# Basic Setup
```{r}

rm(list = setdiff(ls(), lsf.str()))
library(readxl)
library(ggplot2)
library(fmsb)
library(vcd)
library(explore)
library(corrplot)
library(dplyr)
library(car)
library(rstatix)
library(ggpubr)

demo_data_file <- "../data/PredictingOutcomes_ParticipantDemographics.xlsx"
excel_sheets(demo_data_file)
pred_data_file <- "../data/PredictingOutcomes_ParticipantPredictions.xlsx"
excel_sheets(pred_data_file)
strat_data_file <- "../data/PredictingOutcomes_QualitativeStrategyRatings.xlsx"
excel_sheets(strat_data_file)

```

# Data Organization
```{r}

read_excel_allsheets <- function(filename, tibble = FALSE) {
    sheets <- excel_sheets(filename)
    x <- lapply(sheets, function(X) read_excel(filename, sheet = X))
    x <- lapply(x, as.data.frame)
    names(x) <- sheets
    x
}

pred_data <- read_excel_allsheets(pred_data_file)
demo_data <- read_excel_allsheets(demo_data_file)

data <- pred_data
for(i in names(pred_data)) {       # for-loop over columns
  if(i == "KEY") {
    next
  }
    
  data[[i]] <- left_join(pred_data[[i]], demo_data[[i]], by = "participant_id") %>% 
    select(-ends_with(".y"), study = study.x, generator = generator.x, rate = rate.x) 
  data[[i]]$score_prob <- data[[i]]$score_prob1 + data[[i]]$score_prob2 + data[[i]]$score_prob3
  data[[i]]$score_fin <- data[[i]]$score_fin1 + data[[i]]$score_fin2
  
}

anova <- function(df) {
  df <- df %>%
    convert_as_factor(participant_id, generator, terminal_streak_length)
  
  # bxp <- boxplot(
  # df, x = "terminal_streak_length", y = "prediction_recode",
  # color = "generator", palette = "jco"
  # )
  
  #outlier detection
  print(df %>%
    group_by(terminal_streak_length, generator) %>%
    identify_outliers(prediction_recode))

  #Shapiro-Wilk test
  print(df %>%
    group_by(terminal_streak_length, generator) %>%
    shapiro_test(prediction_recode))
  
  #Q-Q plot
  print(ggqqplot(df, "prediction_recode", ggtheme = theme_bw()) +
    facet_grid(terminal_streak_length ~ generator))
  
  #Levene test
  print(df %>%
    group_by(terminal_streak_length) %>%
    levene_test(prediction_recode ~ generator))
  
  #Box-m test
  print(box_m(df[, "prediction_recode", drop = FALSE], df$generator))
  
  #Anova test

  print(sapply(lapply(df, unique), length))
  df$ID <- seq.int(nrow(df))
  print(df)
  res.aov <- 
    anova_test(data = df, 
               formula=prediction_recode~terminal_streak_length*generator*participant_id
               + Error(participant_id/terminal_streak_length), 
               dv = prediction_recode, wid=ID, within = terminal_streak_length,
               between = c(participant_id,generator))
  get_anova_table(res.aov, correction=c("GG"))
  
  # df <- curr_pred_data[c("participant_id", "generator", "terminal_streak_length", "prediction_recode", "gender")]
# leveneTest(`Driving ability score` ~ `Nights of sleep deprivation`, data = df2)

  # aov_orig <- aov(prediction_recode ~ generator * gender * terminal_streak_length + Error(participant_id / terminal_streak_length), data = df)
  # summary(aov_orig)
}

# df$ID <- seq.int(nrow(df))
# df$generator <- as.factor(df$generator)
# df$terminal_streak_length <- as.factor(df$terminal_streak_length)
# res <- anova_test(
#   data = df, dv = prediction_recode, wid = ID,
#   between = generator, within = terminal_streak_length
#   )
# get_anova_table(res.aov)

for(i in names(pred_data)) {       # for-loop over columns
  if(i == "KEY") {
    next
  }
  
  res<-anova(data[[i]])
}
res

```


```{r}
library(dplyr)
for(i in names(pred_data)) {       # for-loop over columns
  if(i == "KEY") {
    next
  }
  new_data <- data[[i]] %>%
    gather(key = "generator", value = "prediction") %>%
    convert_as_factor(participant_id,generator)
}
new_data %>% sample_n_by(generator, prediction_recode, size = 1)

# Average Probability Participants Assigned to Repetition of Terminal Streaks, by Streak Length and Condition
avg_prob_grouped <- function(df){
}

# Proportion of Participants Predicting Repetition of Terminal Streaks, by Streak Length and Condition
#One way Mixed ANOVA
mixed_anova <- function(df) {
  df$generator <- as.factor(df$generator)
  boxplot(df$generator~df$prediction_recode)
  df$participant_id <- as.factor(df$participant_id)
  shapiro.test(df$prediction_recode[0:5000])
  leveneTest(df$prediction_recode~df$generator,data=df)

  # df <- curr_pred_data[c("participant_id", "generator", "terminal_streak_length", "prediction_recode", "gender")]
# leveneTest(`Driving ability score` ~ `Nights of sleep deprivation`, data = df2)
}

for(i in names(pred_data)) {       # for-loop over columns
  if(i == "KEY") {
    next
  }
  res <- mixed_anova(data[[i]])
}

res
```
