---
title: "t-test"
authors: "Debayan Saha (2019113002), Shaurya Dewan (2019101017), Snehal Kumar (2019101003)"
date: "2023-04-23"
output: pdf_document
---

```{r setup}
# Basic Setup


rm(list = setdiff(ls(), lsf.str()))
library(readxl)
library(ggplot2)
library(fmsb)
library(vcd)
library(explore)
library(corrplot)
library(dplyr)
library(car)
library(rstatix)

demo_data_file <- "../data/PredictingOutcomes_ParticipantDemographics.xlsx"
excel_sheets(demo_data_file)
pred_data_file <- "../data/PredictingOutcomes_ParticipantPredictions.xlsx"
excel_sheets(pred_data_file)
strat_data_file <- "../data/PredictingOutcomes_QualitativeStrategyRatings.xlsx"
excel_sheets(strat_data_file)

```

# Data Organization
```{r}

read_excel_allsheets <- function(filename, tibble = FALSE) {
    sheets <- excel_sheets(filename)
    x <- lapply(sheets, function(X) read_excel(filename, sheet = X))
    x <- lapply(x, as.data.frame)
    names(x) <- sheets
    x
}

demo_data <- read_excel_allsheets(demo_data_file)
pred_data <- read_excel_allsheets(pred_data_file)

data <- pred_data
for(i in names(pred_data)) {       # for-loop over columns
  if(i == "KEY") {
    next
  }
    
  data[[i]] <- left_join(pred_data[[i]], demo_data[[i]], by = "participant_id") %>% 
    select(-ends_with(".y"), study = study.x, generator = generator.x, rate = rate.x) 
  data[[i]]$score_prob <- data[[i]]$score_prob1 + data[[i]]$score_prob2 + data[[i]]$score_prob3
  data[[i]]$score_fin <- data[[i]]$score_fin1 + data[[i]]$score_fin2
  
}
```
```{r}
data1A <- data.frame(data[[names(data)[2]]])
data1B <- data.frame(data[[names(data)[3]]])
data2A <- data.frame(data[[names(data)[4]]])
data2B <- data.frame(data[[names(data)[5]]])
data3A <- data.frame(data[[names(data)[6]]])
data3B <- data.frame(data[[names(data)[7]]])
```

# Performing t-tests between Condition on terminal streak lengths

```{r}
# T-test
avg_calc <- function(data, study){
  df <- data.frame()
  search_list <- c("generator", "participant_id", "type", "terminal_streak_length", "prediction_recode")
  search_indices <- which(colnames(data) %in% search_list)
  x <- data.frame(data[,search_indices])
  x <- data.frame(x[which(x$type == "target"),])
  # print(x)
  for(i in unique(x$participant_id)){
    # print(x[which(x$participant_id == i),]$generator[1])
    if(study == 0){
      char = "A"
    }
    else{
      char = "B"
    }
    df <- rbind(df, c(char, x[which(x$participant_id == i),]$generator[1], i, sum(x[which(x$participant_id == i),]$prediction_recode)))
  }
  colnames(df) <- c("study", "generator", "participant_id", "prediction_recode")
  df[,3] <- as.numeric(df[,3])
  if(study == 0)
  {
    df[,4] <- as.numeric(df[,4])/100
    df[,4] <- as.numeric(df[,4])
  }
  else
  {
    df[,4] <- as.numeric(df[,4])
  }
  return(df)
}

ttest <- function(df1,df2){
  res <- list()
  for(i in 2:7){
    df1$participant_id <- as.factor(df1$participant_id)
    df2$participant_id <- as.factor(df2$participant_id)
    df1_bingo = df1$prediction_recode[df1$generator == "bingo" & df1$terminal_streak_length == i]
    df1_stock = df1$prediction_recode[df1$generator == "stock" & df1$terminal_streak_length == i]
    df1_analyst = df1$prediction_recode[df1$generator == "analyst" & df1$terminal_streak_length == i]
    df2_bingo = df2$prediction_recode[df2$generator == "bingo" & df2$terminal_streak_length == i]
    df2_stock = df2$prediction_recode[df2$generator == "stock" & df2$terminal_streak_length == i]
    df2_analyst = df2$prediction_recode[df2$generator == "analyst" & df2$terminal_streak_length == i]
   
  
    # t_stat_bingo_stock <- t.test(df_bingo,df_stock)
    # t_stat_bingo_analyst <- t.test(df_bingo,df_analyst)
    # t_stat_analyst_stock <- t.test(df_analyst,df_stock)
    t_stat_bingo <- t.test(df1_bingo,df2_bingo)
    t_stat_analyst <- t.test(df1_analyst,df2_analyst)
    t_stat_stock <- t.test(df1_stock,df2_stock)
   
    # res1 <- list(t_stat_bingo_stock,t_stat_bingo_analyst,t_stat_analyst_stock)
    # resp <- list((t_stat_bingo_stock)$p.value,(t_stat_bingo_analyst)$p.value,(t_stat_analyst_stock)$p.value)
    out <- paste0("T-test for terminal streak length: ",i)
    print(out)
    res1 <- list(t_stat_bingo,t_stat_analyst,t_stat_stock)
   resp <- list((t_stat_bingo)$p.value,(t_stat_analyst)$p.value,(t_stat_stock)$p.value)
    print(res1)
    res <- append(res,resp)
    # res <- list(res,res1)
    # tstats <- rbind(tstats,tstats_i)
    # test.stat = abs(median(df_bingo)-median(df_stock))
    
  }
    return(res)
}

```
```{r}
print("Study 1A")
# data1A_avg <- avg_calc(data1A, 0)
# print(data1A_avg)
ps <- ttest(data1A, data1B)
print(ps)
# p_bonf <- p.adjust(ps,method="bonferroni",n=length(ps))
# print(p_bonf)
#[1] 0.0162549 0.3120258 0.6248342
#[1] 0.0162549 0.3120258 0.6248342
#[1] 0.0162549 0.3120258 0.6248342
```
```{r}
print("Study 1B")
data1B_avg <- avg_calc(data1B, 1)
ps <- ttest(data1B_avg)
p_bonf <- p.adjust(ps,method="bonferroni",n=length(ps))
print(p_bonf)
```
```{r}
print("Study 2A")
ttest(data1A)
```
```{r}
print("Study 2B")
ttest(data1A)
```
```{r}
print("Study 3A")
ttest(data1A)
```
```{r}
print("Study 3B")
ttest(data1A)
```


```{r}
#T test
```