---
title: "Visualisation"
authors: "Debayan Saha (2019113002), Shaurya Dewan (2019101017), Snehal Kumar (2019101003)"
date: "08/04/2023"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

# Basic Setup
```{r}

rm(list = setdiff(ls(), lsf.str()))
library(readxl)
library(ggplot2)
library(fmsb)
library(vcd)
library(explore)
library(corrplot)
library(dplyr)
library(car)
library(rstatix)
library(rmcorr)
library(ggpubr)
# library(tidyverse)
library(caret)
```
# data assignment
```{r}
demo_data_file <- "../data/PredictingOutcomes_ParticipantDemographics.xlsx"
excel_sheets(demo_data_file)
pred_data_file <- "../data/PredictingOutcomes_ParticipantPredictions.xlsx"
excel_sheets(pred_data_file)
strat_data_file <- "../data/PredictingOutcomes_QualitativeStrategyRatings.xlsx"
excel_sheets(strat_data_file)

```

# Data Organization
```{r}

read_excel_allsheets <- function(filename, tibble = FALSE) {
    sheets <- excel_sheets(filename)
    x <- lapply(sheets, function(X) read_excel(filename, sheet = X))
    x <- lapply(x, as.data.frame)
    names(x) <- sheets
    x
}

demo_data <- read_excel_allsheets(demo_data_file)
pred_data <- read_excel_allsheets(pred_data_file)

data <- pred_data
for(i in names(pred_data)) {       # for-loop over columns
  if(i == "KEY") {
    next
  }
    
  data[[i]] <- left_join(pred_data[[i]], demo_data[[i]], by = "participant_id") %>% 
    select(-ends_with(".y"), study = study.x, generator = generator.x, rate = rate.x) 
  data[[i]]$score_prob <- data[[i]]$score_prob1 + data[[i]]$score_prob2 + data[[i]]$score_prob3
  data[[i]]$score_fin <- data[[i]]$score_fin1 + data[[i]]$score_fin2
  
}
```
# splitting the studies 
```{r}
data1A <- data.frame(data[[names(data)[2]]])
data1B <- data.frame(data[[names(data)[3]]])
data2A <- data.frame(data[[names(data)[4]]])
data2B <- data.frame(data[[names(data)[5]]])
data3A <- data.frame(data[[names(data)[6]]])
data3B <- data.frame(data[[names(data)[7]]])
```
```{r}
# function to create a new dataframe which takes binary prediction
study_b <- function(data){  
  df <- data.frame()
  for (i in 2:7) {
    x <- data[which(data$terminal_streak_length==i),]
    for (gen in levels(as.factor(data$generator))){
      y <- x[which(x$generator==gen),]
      tot <- nrow(y)
      y <- y[which(y$prediction_recode==1),]
      frac <- nrow(y)/tot
      # print(c(frac, tot, gen, i))
      df <- rbind(df, c(i, as.numeric(frac), gen))
    }
  }
  colnames(df) <- c("terminal_streak_length", "prediction_recode", "generator")
  df[,2] <- as.numeric(df[,2])
  # print(df)
  return(df)
}
```
# for visualisation
```{r}
ggboxplot(data1A[which(data1A$type=="target"),], x = "terminal_streak_length", y = "prediction_recode",
color = "generator", palette = "jco") + labs(title = "Study 1A")
```
```{r}
new <- study_b(data1B)
ggplot(new,aes(x=terminal_streak_length,y=prediction_recode,group=generator))+
  geom_point(aes(color=generator))+
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, by = 0.2))+ labs(title = "Study 1B")
```
```{r}
ggboxplot(data2A[which(data2A$type=="target"),], x = "terminal_streak_length", y = "prediction_recode",
color = "generator", palette = "jco") + labs(title = "Study 2A")
```
```{r}
new <- study_b(data2B)
ggplot(new,aes(x=terminal_streak_length,y=prediction_recode,group=generator))+
  geom_point(aes(color=generator))+
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, by = 0.2))+ labs(title = "Study 2B")
```

```{r}
ggboxplot(data3A[which(data3A$type=="target"),], x = "terminal_streak_length", y = "prediction_recode",
color = "generator", palette = "jco") + labs(title = "Study 3A")
```
```{r}
new <- study_b(data3B)
ggplot(new,aes(x=terminal_streak_length,y=prediction_recode,group=generator))+
  geom_point(aes(color=generator))+
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, by = 0.2))+ labs(title = "Study 3B")
```
# for correlation without streaklength
```{r}
ord_corr <- function(data){
  search_list <- c("generator", "gender", "highest_degree", "stocks", "gambling", "score_prob", "score_fin")
  search_indices <- which(colnames(data) %in% search_list)
  x <- data.frame(data[,search_indices])
  x[,1] <- as.factor(x[,1])
  x[,3] <- x[,3]-1
  x[,4] <- x[,4]+1
  x[,5] <- x[,5]+1
  x[] <- sapply(x, as.numeric)
  x[,1] <- x[,1]-1
  # print(x)
  data_cor <- cor(x, method = "spearman")
  print(data_cor)
  return(data_cor)
}
pl_corr <- function(data){
  corr_val <- ord_corr(data)
  corrplot(corr_val, method="color", tl.col = "black", main="Correlation", mar=c(0,0,1,0))
}
pl_corr(data1A)
```
```{r}
pl_corr(data1B)
```


```{r}
pl_corr(data2A)
```


```{r}
pl_corr(data2B)
```


```{r}
pl_corr(data3A)
```


```{r}
pl_corr(data3B)
```

```{r}
# scaled_corr <- function(data){
#   search_list <- c("generator", "age", "gender", "highest_degree", "stocks", "gambling", "score_prob", "score_fin")
#   search_indices <- which(colnames(data) %in% search_list)
#   x <- data.frame(data[,search_indices])
#   x[,1] <- as.factor(x[,1])
#   x[] <- sapply(x, as.numeric)
#   x[] <- sapply(x, scale)
#   # print(x)
#   data_cor <- cor(x, method = "pearson")
#   print(data_cor)
#   return(data_cor)
# }
# pl_scale_corr <- function(data){
#   corr_val <- scaled_corr(data)
#   corrplot(corr_val, method="color", tl.col = "black", main="Correlation", mar=c(0,0,1,0))
# }
# pl_scale_corr(data1A)
```
# ignore this
# ```{r}
# rmocor <- twedt_dist_measures
# dist_rmc_mat <- rmcorr_mat(participant = Subject, 
#                            variables = c("Blindwalk Away",
#                                          "Blindwalk Toward",
#                                          "Triangulated BW",
#                                          "Verbal",
#                                          "Visual matching"),
#                            dataset = twedt_dist_measures,
#                            CI.level = 0.95)
# 
# corrplot(dist_rmc_mat$matrix)
# df <- data.frame(
#   ID = rep(1:5, each = 3),
#   Measure = rep(c("A", "B", "C"), times = 5),
#   Score = rnorm(15)
# )
# 
# # Calculate the repeated measures correlation using rmcorr()
# corr <- rmcorr(df, id = "ID", time = "Measure", method = "spearman")
# 
# # Print the correlation coefficients
# corr$rho
# 
# ```
# important correlation there are 6 windows each with different streaklength
```{r}
separated_corr <- function(data){
  data <- data[which(data$type == "target"),]
  search_list <- c("generator", "prediction_recode", "terminal_streak_length", "age", "gender", "highest_degree", "stocks", "gambling", "score_prob", "score_fin")
  search_indices <- which(colnames(data) %in% search_list)
  x <- data.frame(data[,search_indices])
  x[,which(colnames(x)=="generator")] <- as.factor(x[,which(colnames(x)=="generator")])
  x[,which(colnames(x)=="highest_degree")] <- x[,which(colnames(x)=="highest_degree")]-1
  x[,which(colnames(x)=="stocks")] <- x[,which(colnames(x)=="stocks")]+1
  x[,which(colnames(x)=="gambling")] <- x[,which(colnames(x)=="gambling")]+1
  x[] <- sapply(x, as.numeric)
  x[,which(colnames(x)=="generator")] <- x[,which(colnames(x)=="generator")]-1
  # print(x)
  for(i in 2:7){
    y <- x[which(x$terminal_streak_length == i),]
    search_list <- c("generator", "prediction_recode", "age", "gender", "highest_degree", "stocks", "gambling", "score_prob", "score_fin")
    search_indices <- which(colnames(y) %in% search_list)
    y <- data.frame(y[,search_indices])
    # print(paste0("dataframe y ", i))
    # print(y)
    data_cor <- cor(y, method = "pearson")
    # print(data_cor)
    corrplot(data_cor, tl.col = "black", main=paste0("Correlation_Streaklength ", i), method = "color", mar=c(0,0,1,0))
  }
}
separated_corr(data1A)
```
```{r}
separated_corr(data1B)
```

```{r}
separated_corr(data2A)
```
```{r}
separated_corr(data2B)
```
```{r}
separated_corr(data3A)
```
```{r}
separated_corr(data3B)
```

# Multicollinearity
```{r}
avg_calc <- function(data, study){
  df <- data.frame()
  search_list <- c("generator", "participant_id", "type", "terminal_streak_length", "prediction_recode")
  search_indices <- which(colnames(data) %in% search_list)
  x <- data.frame(data[,search_indices])
  x <- data.frame(x[which(x$type == "target"),])
  # print(x)
  for(i in unique(x$participant_id)){
    # print(x[which(x$participant_id == i),]$generator[1])
    if(study == 0){
      char = "A"
    }
    else{
      char = "B"
    }
    df <- rbind(df, c(char, x[which(x$participant_id == i),]$generator[1], i, sum(x[which(x$participant_id == i),]$prediction_recode)))
  }
  colnames(df) <- c("study", "generator", "participant_id", "prediction_recode")
  df[,3] <- as.numeric(df[,3])
  if(study == 0)
  {
    df[,4] <- as.numeric(df[,4])/100
    df[,4] <- as.numeric(df[,4])
  }
  else
  {
    df[,4] <- as.numeric(df[,4])
  }
  return(df)
}

extract_ivs <- function(data){
  search_list <- c("generator", "gender", "highest_degree", "stocks", "gambling", "score_prob", "score_fin","prediction_recode","terminal_streak_length")
  
  search_indices <- which(colnames(data) %in% search_list)
  x<-data.frame(data[,search_indices])
  x <- data.frame(data[,search_indices])
  x[,which(colnames(x)=="generator")] <- as.factor(x[,which(colnames(x)=="generator")])
  x[,which(colnames(x)=="highest_degree")] <- x[,which(colnames(x)=="highest_degree")]-1
  x[,which(colnames(x)=="stocks")] <- x[,which(colnames(x)=="stocks")]+1
  x[,which(colnames(x)=="gambling")] <- x[,which(colnames(x)=="gambling")]+1
  x[] <- sapply(x, as.numeric)
  x[,which(colnames(x)=="generator")] <- x[,which(colnames(x)=="generator")]-1
  return(x)
}
data1A_avg = avg_calc(data1A,0)
data_1a <- extract_ivs(data1A)
# Data splitting
training.samples <- data_1a$prediction_recode %>%
  createDataPartition(p = 0.8, list = FALSE)
train.data  <- data_1a[training.samples, ]
test.data <- data_1a[-training.samples, ]
# Regression model
model1 <- lm(prediction_recode ~., data = train.data)
# Make predictions
predictions <- model1 %>% predict(test.data)
# Model performance
data.frame(
  RMSE = RMSE(predictions, test.data$prediction_recode),
  R2 = R2(predictions, test.data$prediction_recode)
)
```
```{r}
# VIF score
car::vif(model1)
```